### ISSUE TITLE
Problem on userLogin function at Zabbix 2.4

### ISSUE THREAD

**Issue by HenriqueCaires** [confirm-it-solutions/PhpZabbixApi#8]
At Zabbix 2.4 I've found the error message: 'API error -32602: The "user.login" method must be called without the "auth" parameter.' on executing userLogin.
to resolve this, I've changed the line 215 
from:
'auth'    => ($auth ? $this->auth : ''),
to:
'auth'    => ($auth ? $this->auth : NULL),

**Comment by domibarton** [comment]
Hi

First of all, thank you for your bug report. I'm kinda busy and it's always a pleasure when people help to debug stuff :)

I think there's something wrong with the logic right there. IMO `$auth` is always true on `line 215`, because it was already checked in the if clause we're currently in :)

So I think it should be referenced to `$this->auth` (instance variable) instead of `$auth` (local variable).

```
diff --git a/templates/abstract.tpl.php b/templates/abstract.tpl.php
index eaaf7ae..98ec1f9 100644
--- a/templates/abstract.tpl.php
+++ b/templates/abstract.tpl.php
@@ -212,7 +212,7 @@ abstract class <CLASSNAME_ABSTRACT>
                 'jsonrpc' => '2.0',
                 'method'  => $method,
                 'params'  => $params,
-                'auth'    => ($auth ? $this->auth : ''),
+                'auth'    => ($this->auth ? $this->auth : NULL),
                 'id'      => $this->id
             );
         }
```

I'll commit the fix asap, can you try it again?

Cheers
Domi
